#!/bin/env python3

import os
import sys
import subprocess

def message():

    subprocess.run(['curl',
               '-X',
               'POST',
               '-H',
               "'Content-type: application/json'",
               '--data',
               '{"text":"Job Failed"}',
               "https://hooks.slack.com/services/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"])

if __name__ == "__main__":
	#sys.stderr.write(str(sys.argv))
	message()
